repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--line-length=88]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4 # Use the revision sha / tag you want to point at
    hooks:
      - id: isort
